name: Deploy to Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t lambda_build

      - name: Zip Lambda package
        run: |
          mkdir -p lambda_build
          cp -r app lambda_entry.py lambda_build/
          cd lambda_build
          zip -r ../lambda_function.zip .

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name trendCrawler \
            --zip-file fileb://lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
